name: Update Clone Count Badge

on:
  # Run once a day
  schedule:
    - cron: '0 0 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    
    # *** FIX 1: Grant explicit write permissions to the job's default GITHUB_TOKEN ***
    permissions:
      contents: write 
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # *** FIX 2: Use the default GITHUB_TOKEN that now has write access ***
          token: ${{ secrets.GITHUB_TOKEN }} 

      - name: Fetch Clone Count
        id: fetch_clones
        # Use your high-permission CLONE_TOKEN ONLY for the API fetch step
        run: |
          # Use jq if you don't have it already (add a setup-jq step if needed)
          CLONES_DATA=$(curl -s -H "Authorization: token ${{ secrets.CLONE_TOKEN }}" \
            "https://api.github.com/repos/SudoHopeX/KaliGPT/traffic/clones")
          
          # Extract the count
          COUNT=$(echo "$CLONES_DATA" | jq -r '.count')
          
          # Write the count to a file for Shields.io
          echo "$COUNT" > clones_count.txt

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update clone count badge data"
          file_pattern: clones_count.txt
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
